/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { PrismaService } from "../../prisma/prisma.service";
import { Prisma, Guide as PrismaGuide } from "@prisma/client";
import { GenerateGuideInput } from "../../location/GenerateGuideInput";
import { RetrieveGuideInput } from "../RetrieveGuideInput";
import { GuideCreateInput } from "./GuideCreateInput";
import { StoreGuideInput } from "../StoreGuideInput";

export class GuideServiceBase {
  constructor(protected readonly prisma: PrismaService) {}

  async count(args: Omit<Prisma.GuideCountArgs, "select">): Promise<number> {
    return this.prisma.guide.count(args);
  }

  async guides(args: Prisma.GuideFindManyArgs): Promise<PrismaGuide[]> {
    return this.prisma.guide.findMany(args);
  }
  async guide(args: Prisma.GuideFindUniqueArgs): Promise<PrismaGuide | null> {
    return this.prisma.guide.findUnique(args);
  }
  async createGuide(args: Prisma.GuideCreateArgs): Promise<PrismaGuide> {
    return this.prisma.guide.create(args);
  }
  async updateGuide(args: Prisma.GuideUpdateArgs): Promise<PrismaGuide> {
    return this.prisma.guide.update(args);
  }
  async deleteGuide(args: Prisma.GuideDeleteArgs): Promise<PrismaGuide> {
    return this.prisma.guide.delete(args);
  }
  async GenerateGuide(args: GenerateGuideInput): Promise<string> {
    throw new Error("Not implemented");
  }
  async RetrieveGuide(args: RetrieveGuideInput): Promise<GuideCreateInput[]> {
    throw new Error("Not implemented");
  }
  async StoreGuide(args: StoreGuideInput): Promise<string> {
    throw new Error("Not implemented");
  }
}
